### ISSUE TITLE
Remove social links at bottom of page

### ISSUE THREAD

**Issue by melodykramer** [presidential-innovation-fellows/dap-guide#13]
Hello!

I think the social links at the bottom of the main page transmit a lot of information back to those social networks. We don't use them on 18F pages. If you'd like to link out to the social networks, it's best to do so with text.

Mel

**Comment by stroupaloop** [comment]
Hi @melodykramer Which social links are you referring to at the bottom of the page? ref: dap-guide.apps.cloud.gov

**Comment by melodykramer** [comment]
The website I saw, which may not be the final version, had links to LinkedIn, Twitter, FB, and possibly one more (but they were the social share buttons provided by those social networks.)

**Comment by stroupaloop** [comment]
Gotcha, that was an old version, no social media links are currently
present!

On Wed, Apr 13, 2016 at 10:48 AM, Melody Kramer notifications@github.com
wrote:

> The website I saw, which may not be the final version, had links to
> LinkedIn, Twitter, FB, and possibly one more (but they were the social
> share buttons provided by those social networks.)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/presidential-innovation-fellows/dap-guide/issues/13#issuecomment-209485100

## 

Andrew Stroup
director of product and technology | presidential innovation fellows
pif.gov
