### ISSUE TITLE
Consider hosting on cloud.gov or Federalist

### ISSUE THREAD

**Issue by gboone** [presidential-innovation-fellows/dap-guide#15]
This site, as far as I can tell, is hosted at least partially on strikingly.com. In addition to not having government friendly terms of service, it appears many if not all the static assets on http://www.dapguide.me/ are being loaded off of a CDN. This is a major privacy leak and compliance issue that should be addressed before launching.

Hosting this site on [Federalist](https://federalist.18f.gov) or [cloud.gov](https://cloud.gov) would give the team the same hosting advantages strikingly provides, while also being a government-friendly, secure platform with a support team in house.

Pinging @konklone and @NoahKunin who may have more specific thoughts and a deeper understanding of the underlying technical issues.

**Comment by gboone** [comment]
See #17, #16

**Comment by babycarrot** [comment]
@gboone The strikingly site is a temporary mockup of a USDS compliant one that @stroupaloop is helping me with. Please disregard that
