### ISSUE TITLE
Change tagline

### ISSUE THREAD

**Issue by awfrancisco** [presidential-innovation-fellows/dap-guide#18]
What about changing the tagline from 
"Solving the deficiencies in digital service and product acquisitions for your agency"

to

"Improving digital service and product acquisitions for your agency"

**Comment by babycarrot** [comment]
Love this suggestion

**Comment by awfrancisco** [comment]
Should I make a PR for this change or does someone else need to approve first?

**Comment by babycarrot** [comment]
If you can make a pull request that will be great!

Sent from my iPhone

On Apr 13, 2016, at 9:26 AM, Andre Francisco notifications@github.com
wrote:

Should I make a PR for this change or does someone else need to approve
first?
