### ISSUE TITLE
pick a different color for subtext

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/dap-guide#6]
pick a new color, not 508 compliant

![image](https://cloud.githubusercontent.com/assets/2424551/14328959/2d0efda4-fc07-11e5-8378-4ab0b5937c88.png)

**Comment by babycarrot** [comment]
1. Internal stakeholder design -> human-centered design image [516891658 ](http://www.thinkstockphotos.com/image/stock-photo-cooperation-is-basic-of-good-company/516891658/popup?sq=team%20computer/f=CTPIHVX/s=DynamicRank)
2. Waterfall-based development approach-> Lean and Agile Approaches [516679744](http://www.thinkstockphotos.com/image/stock-photo-group-of-business-people-talking-about-new/516679744/popup?sq=lean%20startup/f=CPIHVX/s=DynamicRank)
3. Closed innovation to open innovation [486809822](http://www.thinkstockphotos.com/image/stock-photo-clever-student-get-inspiration-under-light/486809822/popup?sq=idea/f=CPIHVX/s=DynamicRank)
4. Large, monolithic contracts to smaller, modular contracts [182270075
   ](http://www.thinkstockphotos.com/image/stock-photo-handshake/182270075/popup?sq=contract/f=CPIHVX/s=DynamicRank)

**Comment by babycarrot** [comment]
oh shoot sorry wrong tab ^ ignore

**Comment by babycarrot** [comment]
Color: #fdb81e (would this one work to substitute) 

<img width="812" alt="screen shot 2016-04-08 at 1 01 57 am" src="https://cloud.githubusercontent.com/assets/3394437/14374593/97b92ade-fd25-11e5-86bc-bf6bda42bce1.png">

**Comment by stroupaloop** [comment]
It needs to be 508 compliant, check out this link https://playbook.cio.gov/designstandards/visual-style/#text-accessibility

**Comment by babycarrot** [comment]
#112e51
<img width="249" alt="screen shot 2016-04-12 at 5 46 23 pm" src="https://cloud.githubusercontent.com/assets/3394437/14476573/864a087c-00d6-11e6-8bb5-593b0eb80acf.png">

**Comment by babycarrot** [comment]
@stroupaloop

**Comment by stroupaloop** [comment]
45f9488
